#!/usr/bin/env python3
"""Writes apps/web/site/known_files.json: the files of each game that the bring-your-own web
build accepts from the player, grouped by game (docs/web.md).

    tools/web_known_files.py [--root DIR] [--out FILE] [--previous FILE] [--check]

The list of games, their executables, pak names, texts file names and the SHA-256 of every pak
come from tools/games.json. What games.json does not hold (sizes, and the hashes of
Settings.xml, the menu logo and the executable) is read from the game's files under the data
root ($AS3D_DATA_ROOT or the repository root; layout as in docs/spec/README.md); a value that
cannot be read from the disk stays what the existing output file says, so the file can be
regenerated on a machine that has only some of the games. Only sizes and checksums are written,
never file contents. A dropped file is identified as belonging to a game by its SHA-256.

--check compares instead of writing (exit 1 when the file is out of date).
"""
import argparse
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, "apps", "web", "site", "known_files.json")

# Keep in step with as3d::gameIsPlayable (engine/include/as3d/game_data.h): the page starts only
# these games; the files of the others are accepted and stored.
PLAYABLE = {"as3d"}

GIVES = {
    "Settings.xml": "the intro pages, the version line and the menu logo",
    "logo2s.tga": "the main menu's logo",
    "exe": "the texts of the Information pages, Game Complete and the ranks (only the texts are kept)",
    "texts": "the same texts as the executable",
}


def install_dir(root, key):
    if key == "as3d":
        return os.path.join(root, "third_party_local", "original")
    return os.path.join(root, "third_party_local", "games", key)


def digest(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest(), os.path.getsize(path)


def build(root, previous):
    with open(os.path.join(HERE, "games.json"), encoding="utf-8") as f:
        games = json.load(f)["games"]
    out = {}
    for g in games:
        key = g["key"]
        inst = install_dir(root, key)
        old = (previous.get("games", {}).get(key) or {}).get("files", {})
        files = {}

        def entry(name, where, required, gives=None, sha=None):
            path = os.path.join(inst, where)
            e = {"required": required}
            o = old.get(name, {})
            if os.path.isfile(path):
                h, size = digest(path)
                if sha and h != sha:
                    sys.exit("web_known_files: %s of %s is not the file games.json lists (sha256 %s)" % (name, key, h))
                e.update(size=size, sha256=h)
            elif sha:
                e["sha256"] = sha
                if "size" in o and o.get("sha256") == sha:
                    e["size"] = o["size"]
            elif "sha256" in o:
                e.update({k: o[k] for k in ("size", "sha256") if k in o})
            else:
                return  # not on this machine and never seen: the game has no such file known
            e["where"] = where
            if gives:
                e["gives"] = gives
            files[name] = e

        for pak in g["paks"]:
            entry(pak, "data/" + pak, True, sha=g["pak_sha256"].get(pak))
        entry("Settings.xml", "data/Settings.xml", False, GIVES["Settings.xml"])
        entry("logo2s.tga", "data/gfx/logo2s.tga", False, GIVES["logo2s.tga"])
        entry(g["exe"], g["exe"], False, GIVES["exe"])
        files[g["texts"]] = {"required": False, "where": "made by tools/extract_exe_texts.py", "gives": GIVES["texts"]}
        out[key] = {
            "title": g["title"],
            "version": g["version"],
            "playable": key in PLAYABLE,
            "exe": g["exe"],
            "texts": g["texts"],
            "paks": g["paks"],
            "files": files,
        }
    return {
        "comment": "The files of each game the web version accepts from the player (docs/web.md), generated by "
                   "tools/web_known_files.py from tools/games.json and the game files. Sizes and SHA-256 only; the "
                   "files themselves are never part of the site.",
        "games": out,
    }


def render(doc):
    lines = ['{', '  "comment": %s,' % json.dumps(doc["comment"]), '  "games": {']
    keys = list(doc["games"])
    for gi, key in enumerate(keys):
        g = doc["games"][key]
        lines.append('    %s: {' % json.dumps(key))
        for f in ("title", "version", "playable", "exe", "texts", "paks"):
            lines.append('      %s: %s,' % (json.dumps(f), json.dumps(g[f])))
        lines.append('      "files": {')
        names = list(g["files"])
        for i, n in enumerate(names):
            e = g["files"][n]
            lines.append('        %s: %s%s' % (json.dumps(n), json.dumps(e), "," if i + 1 < len(names) else ""))
        lines.append('      }')
        lines.append('    }' + ("," if gi + 1 < len(keys) else ""))
    # The first game's files again in the flat form of the page's first version (one entry per
    # line, a space after "{"): apps/tests/web_test.cpp reads this section; the page does not.
    lines += ['  },', '  "files": {']
    first = doc["games"]["as3d"]["files"]
    names = list(first)
    for i, n in enumerate(names):
        e = first[n]
        parts = ['"required": %s' % json.dumps(e["required"])]
        for k in ("size", "sha256", "where", "gives"):
            if k in e:
                parts.append('%s: %s' % (json.dumps(k), json.dumps(e[k])))
        lines.append('    %s: { %s }%s' % (json.dumps(n), ", ".join(parts), "," if i + 1 < len(names) else ""))
    lines += ['  }', '}', '']
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=os.environ.get("AS3D_DATA_ROOT") or REPO)
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--previous", help="the file whose values fill in what the disk lacks (default: --out)")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    previous = {}
    prev = a.previous or a.out
    if os.path.isfile(prev):
        with open(prev, encoding="utf-8") as f:
            previous = json.load(f)
    text = render(build(a.root, previous))
    json.loads(text)  # must parse
    if a.check:
        cur = open(a.out, encoding="utf-8").read() if os.path.isfile(a.out) else ""
        if cur != text:
            print("web_known_files: %s is out of date; run tools/web_known_files.py" % a.out, file=sys.stderr)
            return 1
        print("web_known_files: up to date")
        return 0
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("web_known_files: wrote %s" % a.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
